# Generated by Django 4.1.7 on 2023-03-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=300)),
                ('img_alt', models.TextField()),
                ('img_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_img_url', models.CharField(max_length=300)),
                ('post_desc', models.TextField()),
                ('author_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('like_count', models.IntegerField()),
                ('post_date', models.DateField()),
                ('img_list', models.ManyToManyField(to='yeoncrawl.postimg')),
            ],
        ),
    ]
