# Generated by Django 4.1.7 on 2023-04-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_url", models.CharField(blank=True, max_length=300, null=True)),
                ("img_alt", models.TextField(blank=True, null=True)),
                ("img_name", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "std_img_url",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("post_desc", models.TextField(blank=True, null=True)),
                ("author_id", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=300, null=True)),
                ("like_count", models.IntegerField(blank=True, null=True)),
                ("post_date", models.DateField(blank=True, null=True)),
                (
                    "img_list",
                    models.ManyToManyField(
                        blank=True, null=True, to="yeoncrawl.postimg"
                    ),
                ),
            ],
        ),
    ]
