# Generated by Django 4.1.7 on 2023-04-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeoncrawl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_string",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
