# Generated by Django 4.1.7 on 2023-04-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeoncrawl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img_list",
            field=models.ManyToManyField(blank=True, to="yeoncrawl.postimg"),
        ),
    ]
