# Generated by Django 4.1.7 on 2023-04-12 14:00

from django.db import migrations, models
import yeoncrawl.models


class Migration(migrations.Migration):

    dependencies = [
        ("yeoncrawl", "0003_post_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimg",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=yeoncrawl.models.user_directory_path
            ),
        ),
    ]
